"""Initial migration

Revision ID: 6b41f110b0ca
Revises: 
Create Date: 2025-04-15 22:46:01.971847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b41f110b0ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric', sa.Enum('TEMPERATURE', 'CPU_USAGE', 'FINANCIAL_STOCK', name='metric_type_enum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_metric_timestamp', ['metric', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_metric_timestamp')

    op.drop_table('events')
    # ### end Alembic commands ###
